const columns = [
  { col: "Id", checked: true },
  { col: "Media", checked: false },
  { col: "Station", checked: true },
  { col: "Measurement Regime", checked: false },
  { col: "Mobile", checked: false },
  { col: "Assessment Type", checked: false },
  { col: "Station Classification", checked: true },
  { col: "Used AQD", checked: false },
  { col: "Main Emission Sources", checked: false },
  { col: "Traffic Emissions", checked: false },
  { col: "Heating Emissions", checked: false },
  { col: "Industrial Emissions", checked: false },
  { col: "Distance Source", checked: false },
  { col: "Change AEI Stations", checked: false },
  { col: "Begin position", checked: true },
  { col: "End position", checked: false },
  { col: "Logger Id", checked: false },
  { col: "Pollutant", checked: true },
  { col: "Concentration", checked: true },
  { col: "Timestep", checked: true },
  { col: "From Time", checked: false },
  { col: "To Time", checked: false }
];
export default columns;
