FROM python:3.10.9
RUN apt update
RUN apt -y install
WORKDIR /app
COPY api/requirements.txt .
RUN pip install -r requirements.txt
COPY .env ../
COPY api/ ./
ENV PYTHONUNBUFFERED=1
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "3", "--threads", "2", "--timeout", "3600", "app:app"]