services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: raven-api
    container_name: raven-api
    ports:
      - 5000:5000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: raven-client
    container_name: raven-client
    depends_on:
      - api
    ports:
      - "80:80"
