FROM node:18.12.1-alpine as build-stage
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ ./
RUN npm run build 

FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx/nginx.default.conf /etc/nginx/conf.d/default.conf