FROM python:3.10.9
RUN apt update
RUN apt -y install
WORKDIR /app
COPY api/requirements.txt .
RUN pip install -r requirements.txt
COPY api/ ./
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]