class Namespaces:
    xsi = 'http://www.w3.org/2001/XMLSchema-instance'
    gml = 'http://www.opengis.net/gml/3.2'
    aqd = 'http://dd.eionet.europa.eu/schemaset/id2011850eu-1.0'
    ef = 'http://inspire.ec.europa.eu/schemas/ef/3.0'
    base = 'http://inspire.ec.europa.eu/schemas/base/3.3'
    xlink = 'http://www.w3.org/1999/xlink'
    base2 = 'http://inspire.ec.europa.eu/schemas/base2/1.0'
    gco = 'http://www.isotc211.org/2005/gco'
    ad = 'urn:x-inspire:specification:gmlas:Addresses:3.0'
    gn = 'urn:x-inspire:specification:gmlas:GeographicalNames:3.0'
    ompr = 'http://inspire.ec.europa.eu/schemas/ompr/2.0'
    gmd = 'http://www.isotc211.org/2005/gmd'
    sams = 'http://www.opengis.net/samplingSpatial/2.0'
    sam = 'http://www.opengis.net/sampling/2.0'
    om = 'http://www.opengis.net/om/2.0'
    am = 'http://inspire.ec.europa.eu/schemas/am/3.0'
    swe = 'http://www.opengis.net/swe/2.0'
