export const columns = [
  { col: "Id", checked: true },
  { col: "Measurement Type", checked: false },
  { col: "Measurement Method", checked: true },
  { col: "Other Measurement Method", checked: false },
  { col: "Sampling Method", checked: false },
  { col: "Other Sampling Method", checked: false },
  { col: "Analytical Tech", checked: false },
  { col: "Other Analytical Tech", checked: false },
  { col: "Sampling Equipment", checked: false },
  { col: "Measurement Equipment", checked: false },
  { col: "Equiv Demonstration", checked: true },
  { col: "Equiv Demonstration Report", checked: false },
  { col: "Detection Limit", checked: false },
  { col: "Detection Limit Uom", checked: false },
  { col: "Uncertainty Estimate", checked: false },
  { col: "Documentation", checked: false },
  { col: "Qa Report", checked: false },
  { col: "Duration Number", checked: true },
  { col: "Duration Unit", checked: true },
  { col: "Cadence Number", checked: true },
  { col: "Cadence Unit", checked: true },
  { col: "Responsible Authority Id", checked: true },
  { col: "Other Measurement Equipment", checked: false },
  { col: "Other Sampling Equipment", checked: false }
];
export default columns;
