INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999951, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/51', 'Wind velocity', 'Wind velocity');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999952, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/52', 'Wind direction', 'Wind direction');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999953, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/53', 'Pressure', 'Pressure');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999954, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/54', 'Temperature', 'Temperature');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999955, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/55', 'Absolute humidity', 'Absolute humidity');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999956, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/56', 'Mixing height', 'Mixing height');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999958, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/58', 'Relative humidity', 'Relative humidity');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999959, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/59', 'Duration of sunlight', 'Duration of sunlight');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999960, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/60', 'Precipitation', 'Precipitation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999961, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/61', 'Wind component south-north', 'Wind component south-north');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999962, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/62', 'Wind component west-east', 'Wind component west-east');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999963, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/63', 'Wind component vertical', 'Wind component vertical');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999964, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/64', 'Volume of air', 'Volume of air');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999971, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/71', 'Direct solar IR radiation', 'Direct solar IR radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999972, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/72', 'Direct solar UV radiation', 'Direct solar UV radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999973, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/73', 'Direct solar radiation', 'Direct solar radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999974, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/74', 'Global radiation', 'Global radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999975, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/75', 'Diffused radiation', 'Diffused radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999976, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/76', 'Reflected radiation', 'Reflected radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999977, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/77', 'Direct solar visible radiation', 'Direct solar visible radiation');
INSERT INTO "eea_pollutants"(id, uri, label, notation) VALUES (999999, 'http://dd.eionet.europa.eu/vocabulary/aq/meteoparameter/99', 'No meteo measured', 'No meteo measured');
